name: cron

on:
  push:
    branches:
      - master
  schedule:
    - cron: "5 5 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🍽️ Get working copy
        uses: actions/checkout@v4
        with:
          fetch-depth: 1                                                                 
      - name: 🐍 Set up Python 3.10                               
        uses: actions/setup-python@v5                               
        with:                                 
          python-version: '3.10'
      - name: 💿 Install feedparser & pytz                              
        run: pip install -r requirements.txt
      - name: 🍳 Update README
        run: python ${GITHUB_WORKSPACE}/src/main.py
      - name: 🚀 Deploy
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "feat(auto generate): Updated content"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
